### ISSUE TITLE
Jenkins build fails when pushing Docker image for Microgateway

### ISSUE THREAD

**Issue by Savidude** [wso2/kubernetes-pipeline#15]
**Description:**
The docker registry, and organization name should be obtained from the deployment config file such that a tag could be created in order to push to the Docker registry. 

**Affected Product Version:**
 Helm resources for API Microgateway 3.0.1

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-pipeline/pull/17.
