### ISSUE TITLE
Tag each new Docker image with a timestamp in Microgateway

### ISSUE THREAD

**Issue by Savidude** [wso2/kubernetes-pipeline#16]
**Description:**
The newly created images for API Microgateway should be tagged with the current timestamp.

For example, the image `savidude/petstore:v1` should be tagged with something like `savidude/petstore:v1-20190904092619` when being pushed to the Docker registry through Jenkins.

**Affected Product Version:**
 Helm resources for API Microgateway 3.0.1

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-pipeline/pull/17.
