### ISSUE TITLE
Mention helm version in readme

### ISSUE THREAD

**Issue by bhathiya** [wso2/kubernetes-pipeline#40]
**Description:**

The helm version should be mentioned in the docs. eg. [1]. The given commands don't work with helm v3. It gives this error.

    Error: unknown flag: --name

And crd-install hooks are no longer supported in v3.

[1] https://github.com/wso2/kubernetes-pipeline/blob/master/docs/getting-started-mgw.md

**Comment by bhathiya** [comment]
@Aaquiff please note.

**Comment by chamindi-a** [comment]
@Aaquiff: Include the helm version that the setup work in the documentation

**Comment by chirangaalwis** [comment]
Fixed in #55.
