### ISSUE TITLE
Updating JCasC configmap does not reflect changes in Jenkins

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-pipeline#51]
**Description:**
Jenkins configuration as code loads configuration only at startup. When changing the configmap, the pod needs to restart so that the updated configurations are reflected in Jenkins. This could be done using **AUTOMATICALLY ROLL DEPLOYMENTS** [1]

[1] https://helm.sh/docs/howto/charts_tips_and_tricks/

**Comment by Aaquiff** [comment]
Fixed in #50

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-pipeline/pull/50.
