### ISSUE TITLE
[docs.wso2.com] IAM Pipeline documentation issues

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-pipeline#53]
**Description:**
It was experienced that the IAM CI/CD Pipeline official website documentation has the following issues:

In the **Overview** page [1],

- Replicated content: Section **Continuous integration and continuous delivery explained** is replicated
- The Pipeline's architecture diagram does not display the artifact source repository

In the Getting Started page [2],

- Steps **Prepare**, **Experiment** and **Customize** do not direct to the appropriate page links. It would be better, if the relevant step (or verbs) link to the relevant pages.

[1]: [Overview page](https://docs.wso2.com/display/IdentityPipeline/Overview)
[2]: [Get Started With CICD Pipeline](https://docs.wso2.com/display/IdentityPipeline/Get+Started+With+CICD+Pipeline)

**Comment by chirangaalwis** [comment]
Correcting the issue title to `docs.wso2.com`.

**Comment by Aaquiff** [comment]
@chirangaalwis the diagram has been updated.

**Comment by chamindi-a** [comment]
@chirangaalwis: The duplicated content issue was also fixed in https://docs.wso2.com/display/IdentityPipeline/Overview
