### ISSUE TITLE
Dockerfile for Jenkins can be improved

### ISSUE THREAD

**Issue by Aaquiff** [wso2/kubernetes-pipeline#7]
### **Description:**
Dockerfile for the Jenkins image adds additional binaries on top of the Jenkins LTS image. Some of these could be removed to reduce the size of the image.

**Comment by chirangaalwis** [comment]
Addressed in https://github.com/wso2/kubernetes-pipeline/pull/10.

**Comment by chirangaalwis** [comment]
@Aaquiff IMO during this improvement process we should stick to the best practices suggested for Dockerfiles at [1] and [2].

[1]: [Official Dockerfile review guidelines](https://github.com/docker-library/official-images#review-guidelines)
[2]: [Best practices for writing Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)

**Comment by Aaquiff** [comment]
@chirangaalwis can we move this to the next milestone?

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-pipeline/pull/71.
